BattlemonASP/Models/Classes/Battlemon.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BattlemonASP.Models.Classes
{
    public class Battlemon
    {
        public int BattlemonID { get; set; }
        public string Name { get; set; }
        public int HealthPoints { get; set; }
        public int Attack { get; set; }
        public int Defence { get; set; }
        public int Speed { get; set; }
        public string Type { get; set; }
        public string Image { get; set; }
        public string ImageBack { get; set; }

        public Battlemon(int BattlemonID, string Name, int HealthPoints, int Attack, int Defence, int Speed, string Type, string Image, string ImageBack)
        {
            this.BattlemonID = BattlemonID;
            this.Name = Name;
            this.HealthPoints = HealthPoints;
            this.Attack = Attack;
            this.Defence = Defence;
            this.Speed = Speed;
            this.Type = Type;
            this.Image = Image;
            this.ImageBack = ImageBack;
        }

        public Battlemon()
        {

        }
    }

}

BattlemonASP/Models/ViewModels/BattlemonViewModel.cs
using BattlemonASP.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BattlemonASP.Models.ViewModels
{
    public class BattlemonViewModel
    {
        public List<BattlemonDetailViewModel> BvmList { get; set; }
    }
}

BattlemonASP/Controllers/BattlemonController.cs
using Battlemon_ASP.Converters;
using BattlemonASP.DataLayer.Context;
using BattlemonASP.DataLayer.Repositories;
using BattlemonASP.Models.ViewModels;
using BattlemonASP.Models.Classes;
using BattlemonASP.Converters;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using BattlemonASP.DataLayer.Interfaces;

namespace BattlemonASP.Controllers
{
    public class BattlemonController : Controller
    {
        IBattlemonInterface context;
        BattlemonRepo battlemonRepo;
        BattlemonViewModelConverter bvmc = new BattlemonViewModelConverter();
        AttackViewModelConverter avmc = new AttackViewModelConverter();
        public double damage { get; set; }

        //public BattlemonController(IBattlemonInterface context)
        //{
        //  this.context = context;
        //battlemonRepo = new BattlemonRepo(context);
        //}
        public BattlemonController()
        {
            this.context = new BattlemonContext();
            battlemonRepo = new BattlemonRepo(context);
        }

        public IActionResult Index()
        {
            List<Battlemon> monList = battlemonRepo.GetAllBattlemon();
            BattlemonViewModel vm = new BattlemonViewModel()
            {
                BvmList = new List<BattlemonDetailViewModel>()
            };


            foreach (Battlemon c in monList)
            {
                vm.BvmList.Add(bvmc.ViewModelFromBattlemon(c));
            }

            return View(vm);
        }

        public IActionResult BattlemonInfo(int id)
        {
            BattlemonDetailViewModel vm = bvmc.ViewModelFromBattlemon(battlemonRepo.GetBattlemonByID(id));
            return View(vm);
        }

        public IActionResult GetAttack(int id)
        {
            AttackDetailViewModel vm = avmc.ViewModelFromAttack(battlemonRepo.GetAttack(id));
            return View("AttackPartial", vm);
        }

        [HttpGet]
        public IActionResult EditBattlemon(int id)
        {
            Battlemon battlemon = battlemonRepo.GetBattlemonByID(id);
            BattlemonDetailViewModel vm = bvmc.ViewModelFromBattlemon(battlemon);
            return View(vm);
        }

        [HttpPost]
        public IActionResult EditBattlemon(BattlemonDetailViewModel vm)
        {
            Battlemon battlemon = bvmc.ViewModelToBattlemon(vm);
            battlemonRepo.EditBattlemon(battlemon);
            return RedirectToAction("BattlemonInfo", new { id = battlemon.BattlemonID });
        }
    }
}

BattlemonASP/Controllers/OpponentController.cs
using BattlemonASP.DataLayer.Context;
using BattlemonASP.DataLayer.Repositories;
using BattlemonASP.Converters;
using BattlemonASP.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BattlemonASP.DataLayer.Interfaces;

namespace BattlemonASP.Controllers
{
    public class OpponentController : Controller
    {
        IOpponentInterface context;
        OpponentRepo opponentRepo;
        OpponentViewModelConverter bvmc = new OpponentViewModelConverter();
        Random randomOpponent = new Random();
        int a;
        public OpponentController()
        {
            this.context = new OpponentContext();
            opponentRepo = new OpponentRepo(context);
        }

        public IActionResult GetOpponentByID(int id)
        {
            a = randomOpponent.Next(1, 7);
            id = a;
            OpponentDetailViewModel vm = bvmc.ViewModelFromOpponent(opponentRepo.GetOpponentByID(id));
            return View(vm);
        }
    }
}

BattlemonASP/Views/Battlemon/AttackPartial.cshtml
@model BattlemonASP.Models.ViewModels.AttackDetailViewModel
@{
    Layout = null;
}

<div class="col-md-6">
    <h2>AttackPartial</h2>
    <table class="table">
        <thead>
            <tr>
                <th>
                    Attack 1:
                </th>
                <th>
                    Attack 2:
                </th>
                <th>
                    Attack 3:
                </th>
            </tr>
            <tr>
                <th>
                    Attack 4:
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    @Model.attack1
                </td>
                <td>
                    @Model.attack2
                </td>
                <td>
                    @Model.attack3
                </td>
                <td>
                    @Model.attack4
                </td>
            </tr>
        </tbody>
    </table>
</div>

BattlemonASP/Views/Battlemon/BattlemonInfo.cshtml
@{
    ViewData["Title"] = "Battlemon Info";
}
<div class="row">
    <div class="col-md-6">

        <p class="font-weight-bold"><font size="6">Battlemon Info</font></p>

        @if (Model.Name == "LittleCat" || Model.Name == "Kens" || Model.Name == "Shysto")
        {<div>
                <div><img src="~/images/@Model.Image" style="position:absolute; top:100px; right:850px" height="200" width="350"></div>
            </div>
        }
        else
        {
            <div>
                <div><img src="~/images/@Model.Image" style="position:absolute; top:100px; right:1000px" height="200" width="200"></div>
            </div>
        }
        <div>
            <div>@Model.Name</div>
        </div>
        <br />
        <div>
            <div>@Model.Type</div>
        </div>
        <br />
        <div>
            <div>Attack stat: @Model.Attack</div>
        </div>
        <br />
        <div>
            <div>Defence stat: @Model.Defence</div>
        </div>
        <br />
        <div>Speed stat: @Model.Speed</div>
        <br />

        <a onclick="ShowAttacks(@Model.BattlemonID)">Show attacks</a>
    </div>
    <div class="col-md-6">
        <div id="changespace" />
    </div>
</div>
@*<script type="text/javascript">
    window.onload = function () {
        ShowAttacks(BattlemonID = @Model.BattlemonID);
    }
</script>*@

BattlemonASP/Views/Battlemon/EditBattlemon.cshtml
@model BattlemonASP.Models.ViewModels.BattlemonDetailViewModel
@{
    ViewData["Title"] = "EditBattlemon";
}

<h2>EditBattlemon</h2>

<h4>BattlemonDetailViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditBattlemon">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" hidden>
                <label asp-for="BattlemonID" class="control-label"></label>
                <input asp-for="BattlemonID" class="form-control" />
                <span asp-validation-for="BattlemonID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HealthPoints" class="control-label"></label>
                <input asp-for="HealthPoints" class="form-control" />
                <span asp-validation-for="HealthPoints" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Attack" class="control-label"></label>
                <input asp-for="Attack" class="form-control" />
                <span asp-validation-for="Attack" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Defence" class="control-label"></label>
                <input asp-for="Defence" class="form-control" />
                <span asp-validation-for="Defence" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Speed" class="control-label"></label>
                <input asp-for="Speed" class="form-control" />
                <span asp-validation-for="Speed" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">cancel</a>
</div>

BattlemonASP/Views/Battlemon/GetAttack.cshtml
@{
    ViewData["Title"] = "GetAttack";
}

<center>
    <h2>@Model.name</h2>

    <font size="4"><div>@Model.attack1 &nbsp &nbsp @Model.attack2</div><p>
        <div>@Model.attack3 &nbsp &nbsp @Model.attack4</div></font>

</center>

BattlemonASP/Views/Battlemon/Index.cshtml
@{
    ViewData["Title"] = "Battlemon";
}
<div class="row">
    <div class="col-md-6">
        @foreach (var mon in Model.BvmList)
        {
            <br />
            @if (mon.Name == "LittleCat" || mon.Name == "Kens" || mon.Name == "Shysto")
            {
                <a asp-controller="Battlemon" asp-action="BattlemonInfo" asp-route-id="@mon.BattlemonID"><img src="~/images/@mon.Image" height="35" width="55"></a>
            }
            else
            {
                <a asp-controller="Battlemon" asp-action="BattlemonInfo" asp-route-id="@mon.BattlemonID"><img src="~/images/@mon.Image" height="40" width="40"></a>
            }
            <div><font size="4"><a asp-controller="Battlemon" asp-action="BattlemonInfo" asp-route-id="@mon.BattlemonID"><font color="black">@mon.Name</font></a></font></div>
            if (User.IsInRole("Admin"))
            {
                <div><font size="4"><a asp-controller="Battlemon" asp-action="EditBattlemon" asp-route-id="@mon.BattlemonID">Edit Battlemon</a></font></div>
            }

            <a asp-controller="Opponent" asp-action="GetOpponentByID" asp-route-id="">kip</a>
            <a onclick="ShowAttacks(@mon.BattlemonID)">Show attacks</a>

        }
    </div>
    <div class="col-md-6">
        <div id="testspace" />
    </div>
</div>